CREATE TABLE stadiums (
    NAME VARCHAR(100) PRIMARY KEY,
    CITY VARCHAR(100),
    COUNTRY VARCHAR(100),
    CAPACITY INTEGER
);

CREATE TABLE teams (
    TEAM_NAME VARCHAR(100) PRIMARY KEY,
    COUNTRY VARCHAR(100),
    HOME_STADIUM VARCHAR(100),
    FOREIGN KEY (HOME_STADIUM) REFERENCES stadiums(NAME)
);

CREATE TABLE players (
    PLAYER_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    NATIONALITY VARCHAR(100),
    DOB DATE,
    TEAM VARCHAR(100),
    JERSEY_NUMBER INTEGER,
    POSITION VARCHAR(50),
    HEIGHT DECIMAL(5,2),
    WEIGHT DECIMAL(5,2),
    FOOT VARCHAR(10),
    FOREIGN KEY (TEAM) REFERENCES teams(TEAM_NAME)
);

CREATE TABLE managers (
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    NATIONALITY VARCHAR(100),
    DOB DATE,
    TEAM VARCHAR(100),
    PRIMARY KEY (FIRST_NAME, LAST_NAME),
    FOREIGN KEY (TEAM) REFERENCES teams(TEAM_NAME)
);

CREATE TABLE matches (
    MATCH_ID SERIAL PRIMARY KEY,
    SEASON VARCHAR(20),
    DATE_TIME TIMESTAMP,
    HOME_TEAM VARCHAR(100),
    AWAY_TEAM VARCHAR(100),
    STADIUM VARCHAR(100),
    HOME_TEAM_SCORE INTEGER,
    AWAY_TEAM_SCORE INTEGER,
    PENALTY_SHOOT_OUT BOOLEAN,
    ATTENDANCE INTEGER,
    FOREIGN KEY (HOME_TEAM) REFERENCES teams(TEAM_NAME),
    FOREIGN KEY (AWAY_TEAM) REFERENCES teams(TEAM_NAME),
    FOREIGN KEY (STADIUM) REFERENCES stadiums(NAME)
);

CREATE TABLE goals (
    GOAL_ID SERIAL PRIMARY KEY,
    MATCH_ID INTEGER,
    PID INTEGER,
    DURATION INTEGER,
    ASSIST INTEGER,
    GOAL_DESC TEXT,
    FOREIGN KEY (MATCH_ID) REFERENCES matches(MATCH_ID),
    FOREIGN KEY (PID) REFERENCES players(PLAYER_ID),
    FOREIGN KEY (ASSIST) REFERENCES players(PLAYER_ID)
);